version: '3.3'

#Persistência do container
volumes:
  database:

services:
  app:
    build: .
    container_name: "steq-api"
    command: sh -c "npm start"
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app


 
    
